@startuml
class Order {
    + OrderId : int <<get>> <<set>>
    + CustomerId : int <<get>> <<set>>
    + OrderDate : DateTime <<get>> <<set>>
    + Status : OrderStatus <<get>> <<set>>
    + TotalPrice : decimal <<get>> <<set>>
    + DeliveryAddress : string <<get>> <<set>>
    + OrderProducts : ICollection<OrderProduct> <<get>> <<set>>
}
@enduml
