@startuml
class User {
    + UserId : int <<get>> <<set>>
    + FullName : string <<get>> <<set>>
    + Login : string? <<get>> <<set>>
    + Password : string? <<get>> <<set>>
    + Email : string? <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + isAdmin : bool <<get>> <<set>>
    + Orders : List<Order> <<get>> <<set>>
}
@enduml
