@startuml
class OrderService {
    + OrderService(context:ApplicationDBContext)
    + <<async>> AddOrder(model:OrderDTO) : Task
    + <<async>> GetOrder(id:int) : Task<Order>
    + <<async>> UpdateOrder(id:int, model:OrderDTO) : Task
    + <<async>> DeleteOrder(id:int) : Task
    + <<async>> GetAllOrders() : Task<List<Order>>
    + <<async>> GetOrdersByUserId(userId:int) : Task<List<Order>>
}
BaseService <|-- OrderService
@enduml
